# Generated by Django 3.1.1 on 2020-09-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200914_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='name',
        ),
    ]
