# Generated by Django 3.1.1 on 2020-09-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_achievements_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='task',
        ),
    ]
