# Generated by Django 3.1.1 on 2020-09-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200914_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='task',
            new_name='todo',
        ),
    ]
