# Generated by Django 3.1.1 on 2020-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200914_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='objective',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
